FROM tomcat:9.0
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
RUN sed -i 's/\r$//' mvnw
RUN chmod +x mvnw
RUN ./mvnw install -DskipTests
COPY /target/myproject-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/